---
resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/cdavisafc/concourse-examples.git

jobs:
- name: job-do-something-with-git-repo
  public: true
  plan:
  - get: git-resource
    trigger: true
  - task: pwd
    file: git-resource/sample-tasks/pwd.yml
  - task: ls
    file: git-resource/sample-tasks/ls.yml
